language: go

go:
 - 1.11
 - tip

env:
  global:
    - GO111MODULE=on

branches:
  only:
    - master

install:
  - go get golang.org/x/lint/golint

script:
  - golint -set_exit_status
  - go test -v
